import re
p=re.compile('[\d]')
m=p.search('7')
print(m)
p=re.compile('\d')
m=p.search('7')
print(m)
p=re.compile('\D')
m=p.search('a')
print(m)
p=re.compile('[\w]')
m=p.search('K')
print(m)
p=re.compile('\w')
m=p.search('K')
print(m)
p=re.compile('\W')
m=p.search(' ')
print(m)
p=re.compile('[\s]')
m=p.search(' ')
print(m)
p=re.compile('\s')
m=p.search(' ')
print(m)
p=re.compile('\S')
m=p.search('0')
print(m)
